// Generated by TileLang 0.1.9.
// Source: deps/vllm/vllm/model_executor/layers/mhc.py (`mhc_pre_big_fuse_tilelang`)
// Shape constants used: hidden_size=4096, rms_eps=1e-06, hc_pre_eps=1e-06, hc_sinkhorn_eps=1e-06, hc_post_mult_value=2.0, sinkhorn_repeat=20, n_splits=16, hc_mult=4.
// `num_tokens` is dynamic (kernel parameter), so dispatch grid is data-dependent.

#include <math_constants.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void mhc_pre_big_fuse_tilelang_kernel(float* comb_mix, const float* gemm_out_mul, const float* gemm_out_sqrsum, const float* hc_base, const float* hc_scale, bfloat16_t* layer_input, float* post_mix, const bfloat16_t* residual, int num_tokens);
extern "C" __global__ void __launch_bounds__(96, 1) mhc_pre_big_fuse_tilelang_kernel(float* comb_mix, const float* gemm_out_mul, const float* gemm_out_sqrsum, const float* hc_base, const float* hc_scale, bfloat16_t* layer_input, float* post_mix, const bfloat16_t* residual, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float mixes[1];
  float rms[1];
  float cm[1];
  float row_max[1];
  float row_sum[1];
  float col_sum[1];
  bfloat16_t residual_local_cast_1[4];
  float xs_local_cast[4];
  bfloat16_t residual_local_cast_3[4];
  float xs_local_cast_2[4];
  float xl[32];
  float ol[8];
  bfloat16_t residual_local_cast_5[4];
  float xs_local_cast_4[4];
  bfloat16_t layer_input_local_cast_6[4];
  bfloat16_t layer_input_local_cast_7[4];
  bfloat16_t layer_input_local_cast_8[4];
  cudaGridDependencySynchronize();
  mixes[0] = 0x0p+0f/*0.000000e+00*/;
  rms[0] = 0x0p+0f/*0.000000e+00*/;
  for (int i_split = 0; i_split < 16; ++i_split) {
    rms[0] = (rms[0] + gemm_out_sqrsum[((((int64_t)i_split) * ((int64_t)num_tokens)) + ((int64_t)((int)blockIdx.x)))]);
  }
  rms[0] = rsqrtf(((rms[0] / 0x1p+14f/*1.638400e+04*/) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
  mixes[0] = 0x0p+0f/*0.000000e+00*/;
  for (int i_split_1 = 0; i_split_1 < 16; ++i_split_1) {
    mixes[0] = (mixes[0] + gemm_out_mul[(((((int64_t)((int)blockIdx.x)) * (int64_t)24) + ((((int64_t)i_split_1) * ((int64_t)num_tokens)) * (int64_t)24)) + (((int64_t)((int)threadIdx.x)) % (int64_t)24))]);
  }
  mixes[0] = (mixes[0] * rms[0]);
  if ((((int)threadIdx.x) / 24) == 0) {
    ((float*)buf_dyn_shmem)[(((int)threadIdx.x) % 24)] = mixes[0];
  }
  __syncthreads();
  if (((int)threadIdx.x) < 32) {
    if (((int)threadIdx.x) < 4) {
      post_mix[((((int64_t)((int)blockIdx.x)) * (int64_t)4) + ((int64_t)((int)threadIdx.x)))] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((((float*)buf_dyn_shmem)[(((int)threadIdx.x) + 4)] * hc_scale[1]) + hc_base[(((int)threadIdx.x) + 4)]))))) * 0x1p+1f/*2.000000e+00*/);
    }
    cm[0] = ((((float*)buf_dyn_shmem)[((((int)threadIdx.x) & 15) + 8)] * hc_scale[2]) + hc_base[((((int)threadIdx.x) & 15) + 8)]);
    row_max[0] = -CUDART_INF_F;
    row_max[0] = max(row_max[0], cm[0]);
    row_max[0] = tl::AllReduce<tl::MaxOp, 4, 1, 0, tl::NamedBarrier<32>>::run(row_max[0]);
    cm[0] = expf((cm[0] - row_max[0]));
    row_sum[0] = 0x0p+0f/*0.000000e+00*/;
    row_sum[0] = (row_sum[0] + cm[0]);
    row_sum[0] = tl::AllReduce<tl::SumOp, 4, 1, 0, tl::NamedBarrier<32>>::run(row_sum[0]);
    cm[0] = ((cm[0] / row_sum[0]) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/);
    col_sum[0] = 0x0p+0f/*0.000000e+00*/;
    col_sum[0] = (col_sum[0] + cm[0]);
    col_sum[0] = tl::AllReduce<tl::SumOp, 16, 4, 0, tl::NamedBarrier<32>>::run(col_sum[0]);
    cm[0] = (cm[0] / (col_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
    for (int __1 = 0; __1 < 19; ++__1) {
      row_sum[0] = 0x0p+0f/*0.000000e+00*/;
      row_sum[0] = (row_sum[0] + cm[0]);
      row_sum[0] = tl::AllReduce<tl::SumOp, 4, 1, 0, tl::NamedBarrier<32>>::run(row_sum[0]);
      cm[0] = (cm[0] / (row_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
      col_sum[0] = 0x0p+0f/*0.000000e+00*/;
      col_sum[0] = (col_sum[0] + cm[0]);
      col_sum[0] = tl::AllReduce<tl::SumOp, 16, 4, 0, tl::NamedBarrier<32>>::run(col_sum[0]);
      cm[0] = (cm[0] / (col_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
    }
    if ((((int)threadIdx.x) >> 4) == 0) {
      comb_mix[((((int64_t)((int)blockIdx.x)) * (int64_t)16) + (((int64_t)((int)threadIdx.x)) & (int64_t)15))] = cm[0];
    }
  } else {
    if (((int)threadIdx.x) < 36) {
      ((float*)buf_dyn_shmem)[(((int)threadIdx.x) + 4088)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((((float*)buf_dyn_shmem)[(((int)threadIdx.x) - 32)] * hc_scale[0]) + hc_base[(((int)threadIdx.x) - 32)]))))) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/);
    }
    #pragma unroll
    for (int i = 0; i < 8; ++i) {
      *(uint2*)(residual_local_cast_1 + 0) = *(uint2*)(residual + (((((int64_t)((int)blockIdx.x)) * (int64_t)16384) + ((((int64_t)i) >> (int64_t)1) * (int64_t)4096)) + (((((((int64_t)i) * (int64_t)64) + ((int64_t)((int)threadIdx.x))) + (int64_t)96) & (int64_t)127) * (int64_t)4)));
      float4 __2;
      uint2 v_ = *(uint2*)(residual_local_cast_1 + 0);
      ((float2*)(&__2))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
      ((float2*)(&__2))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
      *(float4*)(xs_local_cast + 0) = __2;
      *(float4*)(((float*)buf_dyn_shmem) + ((((i >> 1) * 512) + (((((i * 64) + ((int)threadIdx.x)) + 96) & 127) * 4)) + 24)) = *(float4*)(xs_local_cast + 0);
    }
    tl::cp_async_commit();
    #pragma unroll
    for (int i_1 = 0; i_1 < 8; ++i_1) {
      *(uint2*)(residual_local_cast_3 + 0) = *(uint2*)(residual + ((((((int64_t)((int)blockIdx.x)) * (int64_t)16384) + ((((int64_t)i_1) >> (int64_t)1) * (int64_t)4096)) + (((((((int64_t)i_1) * (int64_t)64) + ((int64_t)((int)threadIdx.x))) + (int64_t)96) & (int64_t)127) * (int64_t)4)) + (int64_t)512));
      float4 __3;
      uint2 v__1 = *(uint2*)(residual_local_cast_3 + 0);
      ((float2*)(&__3))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[0]);
      ((float2*)(&__3))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[1]);
      *(float4*)(xs_local_cast_2 + 0) = __3;
      *(float4*)(((float*)buf_dyn_shmem) + ((((i_1 >> 1) * 512) + (((((i_1 * 64) + ((int)threadIdx.x)) + 96) & 127) * 4)) + 2072)) = *(float4*)(xs_local_cast_2 + 0);
    }
    tl::cp_async_commit();
    for (int i0_h = 0; i0_h < 6; ++i0_h) {
      tl::cp_async_wait<1>();
      tl::__sync_thread_partial<3, 64>();
      #pragma unroll
      for (int i_2 = 0; i_2 < 8; ++i_2) {
        *(float4*)(xl + (i_2 * 4)) = *(float4*)(((float*)buf_dyn_shmem) + (((((i0_h & 1) * 2048) + (i_2 * 256)) + (((int)threadIdx.x) * 4)) - 104));
      }
      #pragma unroll
      for (int i_3 = 0; i_3 < 8; ++i_3) {
        *(uint2*)(residual_local_cast_5 + 0) = *(uint2*)(residual + (((((((int64_t)((int)blockIdx.x)) * (int64_t)16384) + ((((int64_t)i_3) >> (int64_t)1) * (int64_t)4096)) + (((int64_t)i0_h) * (int64_t)512)) + (((((((int64_t)i_3) * (int64_t)64) + ((int64_t)((int)threadIdx.x))) + (int64_t)96) & (int64_t)127) * (int64_t)4)) + (int64_t)1024));
        float4 __4;
        uint2 v__2 = *(uint2*)(residual_local_cast_5 + 0);
        ((float2*)(&__4))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[0]);
        ((float2*)(&__4))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[1]);
        *(float4*)(xs_local_cast_4 + 0) = __4;
        *(float4*)(((float*)buf_dyn_shmem) + (((((i0_h & 1) * 2048) + ((i_3 >> 1) * 512)) + (((((i_3 * 64) + ((int)threadIdx.x)) + 96) & 127) * 4)) + 24)) = *(float4*)(xs_local_cast_4 + 0);
      }
      tl::cp_async_commit();
      #pragma unroll
      for (int i_4 = 0; i_4 < 2; ++i_4) {
        float broadcast_var = 0x0p+0f/*0.000000e+00*/;
        *(float4*)(ol + (i_4 * 4)) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      }
      for (int i_hc = 0; i_hc < 4; ++i_hc) {
        float pre = ((float*)buf_dyn_shmem)[(i_hc + 4120)];
        #pragma unroll
        for (int i_5 = 0; i_5 < 8; ++i_5) {
          ol[i_5] = (ol[i_5] + (pre * xl[((i_hc * 8) + i_5)]));
        }
      }
      #pragma unroll
      for (int i_6 = 0; i_6 < 2; ++i_6) {
        uint2 __5;
        float4 v__3 = *(float4*)(ol + (i_6 * 4));
        (reinterpret_cast<__nv_bfloat162*>(&__5))[0] = __float22bfloat162_rn(((float2*)(&v__3))[0]);
        (reinterpret_cast<__nv_bfloat162*>(&__5))[1] = __float22bfloat162_rn(((float2*)(&v__3))[1]);
        *(uint2*)(layer_input_local_cast_6 + 0) = __5;
        *(uint2*)(layer_input + (((((((int64_t)((int)blockIdx.x)) * (int64_t)4096) + (((int64_t)i0_h) * (int64_t)512)) + (((int64_t)i_6) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)4)) - (int64_t)128)) = *(uint2*)(layer_input_local_cast_6 + 0);
      }
    }
    tl::cp_async_wait<1>();
    tl::__sync_thread_partial<3, 64>();
    #pragma unroll
    for (int i_7 = 0; i_7 < 8; ++i_7) {
      *(float4*)(xl + (i_7 * 4)) = *(float4*)(((float*)buf_dyn_shmem) + (((i_7 * 256) + (((int)threadIdx.x) * 4)) - 104));
    }
    #pragma unroll
    for (int i_8 = 0; i_8 < 2; ++i_8) {
      float broadcast_var_1 = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(ol + (i_8 * 4)) = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
    }
    for (int i_hc_1 = 0; i_hc_1 < 4; ++i_hc_1) {
      float pre_1 = ((float*)buf_dyn_shmem)[(i_hc_1 + 4120)];
      #pragma unroll
      for (int i_9 = 0; i_9 < 8; ++i_9) {
        ol[i_9] = (ol[i_9] + (pre_1 * xl[((i_hc_1 * 8) + i_9)]));
      }
    }
    #pragma unroll
    for (int i_10 = 0; i_10 < 2; ++i_10) {
      uint2 __6;
      float4 v__4 = *(float4*)(ol + (i_10 * 4));
      (reinterpret_cast<__nv_bfloat162*>(&__6))[0] = __float22bfloat162_rn(((float2*)(&v__4))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__6))[1] = __float22bfloat162_rn(((float2*)(&v__4))[1]);
      *(uint2*)(layer_input_local_cast_7 + 0) = __6;
      *(uint2*)(layer_input + ((((((int64_t)((int)blockIdx.x)) * (int64_t)4096) + (((int64_t)i_10) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)4)) + (int64_t)2944)) = *(uint2*)(layer_input_local_cast_7 + 0);
    }
    tl::cp_async_wait<0>();
    tl::__sync_thread_partial<3, 64>();
    #pragma unroll
    for (int i_11 = 0; i_11 < 8; ++i_11) {
      *(float4*)(xl + (i_11 * 4)) = *(float4*)(((float*)buf_dyn_shmem) + (((i_11 * 256) + (((int)threadIdx.x) * 4)) + 1944));
    }
    #pragma unroll
    for (int i_12 = 0; i_12 < 2; ++i_12) {
      float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(ol + (i_12 * 4)) = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
    }
    for (int i_hc_2 = 0; i_hc_2 < 4; ++i_hc_2) {
      float pre_2 = ((float*)buf_dyn_shmem)[(i_hc_2 + 4120)];
      #pragma unroll
      for (int i_13 = 0; i_13 < 8; ++i_13) {
        ol[i_13] = (ol[i_13] + (pre_2 * xl[((i_hc_2 * 8) + i_13)]));
      }
    }
    #pragma unroll
    for (int i_14 = 0; i_14 < 2; ++i_14) {
      uint2 __7;
      float4 v__5 = *(float4*)(ol + (i_14 * 4));
      (reinterpret_cast<__nv_bfloat162*>(&__7))[0] = __float22bfloat162_rn(((float2*)(&v__5))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__7))[1] = __float22bfloat162_rn(((float2*)(&v__5))[1]);
      *(uint2*)(layer_input_local_cast_8 + 0) = __7;
      *(uint2*)(layer_input + ((((((int64_t)((int)blockIdx.x)) * (int64_t)4096) + (((int64_t)i_14) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)4)) + (int64_t)3456)) = *(uint2*)(layer_input_local_cast_8 + 0);
    }
  }
  cudaTriggerProgrammaticLaunchCompletion();
}

